<a href="https://colab.research.google.com/github/seonghaiiiii/aipython/blob/main/240109.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
# 1차원 배열
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
# 2차원 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# 배열의 형태, 차원, 데이터 타입 확인
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Data Type:", arr2d.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [11]:
# 리스트와 array 타입 확인하기
import numpy as np
lst =[1,2,3]
arr = np.array(lst)
print(type(lst), lst)
print(type(arr), arr)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'> [1 2 3]


In [14]:
import numpy as np
# 0부터 9까지
arr = np.arange(10)
print(arr)
# 2부터 19까지, 간격은 2
arr = np.arange(2, 20, 2)
print(arr)

print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
# 1차원 배열
zeros_1d = np.zeros(5)
print(zeros_1d)
# 2차원 배열
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
import numpy as np
# 1차원 배열
ones_1d = np.ones(5)
print(ones_1d)
# 2차원 배열
ones_2d = np.ones((3, 4))
print(ones_2d)
print(type(ones_1d))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
# 1차원 배열
arr_1d = np.random.rand(5)
print(arr_1d)
# 2차원 배열
arr_2d = np.random.rand(2, 3)
print(arr_2d)

[0.33603534 0.24878265 0.4922707  0.42979957 0.63698534]
[[0.03758236 0.97538095 0.47345758]
 [0.68301549 0.23644314 0.21295798]]


In [27]:
import numpy as np
# 0부터 1까지 5개의 값
arr = np.linspace(0, 1, 5)
print(arr)
print(type(arr))

[0.   0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>


In [30]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("합:",np.sum(arr))
print("행의 원소 합: ",np.sum(arr, axis=0))
print("열의 원소 합: ",np.sum(arr, axis=1))
print("평균:",np.mean(arr))
print("행의 원소 평균: ",np.mean(arr, axis=0))
print("열의 원소 평균: ",np.mean(arr, axis=1))
print("최대:",np.max(arr))
print("최소:",np.min(arr))
print("행의 원소 최대값: ",np.max(arr, axis=0))
print("행의 원소 최소값: ",np.min(arr, axis=0))
print("열의 원소 최대값: ",np.max(arr, axis=1))
print("열의 원소 최소값: ",np.min(arr, axis=1))
print(np.argmax(arr))
print(np.argmin(arr))
print("분산:",np.var(arr))
print("표준편차:",np.std(arr))


[[1 2 3]
 [4 5 6]]
합: 21
행의 원소 합:  [5 7 9]
열의 원소 합:  [ 6 15]
평균: 3.5
행의 원소 평균:  [2.5 3.5 4.5]
열의 원소 평균:  [2. 5.]
최대: 6
최소: 1
행의 원소 최대값:  [4 5 6]
행의 원소 최소값:  [1 2 3]
열의 원소 최대값:  [3 6]
열의 원소 최소값:  [1 4]
5
0
분산: 2.9166666666666665
표준편차: 1.707825127659933


In [41]:
arr1 = np.arange(1,10,2)
print(arr1)
print()
arr2 = np.ones((3,4))
print(arr2)
print()
arr3 = np.linspace(0,1,10)
print(arr3)

[1 3 5 7 9]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [42]:
arr1 = np.ones([3,4])
print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [44]:
arr1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [71]:
a = np.arange(1,26).reshape(5,5)
print(a)
print()
# a 모양을 출력해보자
print(a.shape)
print()
# 19 값을 추출해보자
print(a[3,3])
print()
# [[1,2],[6,7]] 값을 추출해보자
print(a[:2,:2])
print()
# [[19,20],[24,25]] 값을 추출해보자
print(a[3:5,3:5])
print()
# 0축(모든열)의 첫번째 행과 두번째 행을 추출해보자
print(a[0:2])
print()
# 1축(모든행)의 마지막 열과 마지막 직전 열을 추출해보자
#print(a[0:5,3:5])
print(a[:,-2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

(5, 5)

19

[[1 2]
 [6 7]]

[[19 20]
 [24 25]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [72]:
arr=np.array([[1,2,3],[4,5,6]])
arr_T=arr.transpose()
arr_F=arr.flatten()
arr_R=arr_F.reshape(3,2)
print(arr)
print(arr_T)
print(arr_F)
print(arr_R)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [80]:
a = np.arange(1,37).reshape(3,3,4)
print(a)
print(a.shape)
print(a.size)
print(a.reshape(3,4,3))
print(a.flatten())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
